In [73]:
import pandas as pd
import numpy as np
import streamlit as st

In [3]:
pd.__version__

'3.0.2'

In [10]:
header = st.header("Topics")
print(header)

2026-04-26 10:30:39.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 10:30:39.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 10:30:39.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

## Topics
# Create Dataframe
# Basic Dataframe understinding
# Save and Load data from csv
# Rows & Coloumns - Selection
# Filter dataframe
# Rows & Coloumns - Operation (Add, update, deelete)
# Working with data value
# Handeling missing values
# Aggregation and group by
# Concatenate and Merge Dataframe (JSON)
# AI and ChatGPT

 # 1. Create Dataframe

In [18]:
arr = np.array( ["Mahesh", "Arun", "Bhushan"])
frame = pd.DataFrame(arr, columns=["Students"])
print(frame)

  Students
0   Mahesh
1     Arun
2  Bhushan

In [19]:
data = {
    "Name":["Mahesh", "Arun", "Bhushan", "Amol"],
    "Age": [20, 21, 22, 21],
    "Salery":[5000, 6000, 7000, 8000]
}

In [46]:
df = pd.DataFrame(data)
print(df)

      Name  Age  Salery
0   Mahesh   20    5000
1     Arun   21    6000
2  Bhushan   22    7000
3     Amol   21    8000

## 2. Basic Dataframe Understanding

In [32]:
df.head(2) # for top row
df.tail(2) # for bottom row
df.shape # for finf numbers of rows and coloumns
df.columns # for find coloumns
df.rename(columns={'Salery': 'Monthly Salery'}) # rename the coloumns
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salery  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 249.0 bytes

             Age       Salery
count   4.000000     4.000000
mean   21.000000  6500.000000
std     0.816497  1290.994449
min    20.000000  5000.000000
25%    20.750000  5750.000000
50%    21.000000  6500.000000
75%    21.250000  7250.000000
max    22.000000  8000.000000

## 3. Save and Load data from csv

In [43]:
df.to_csv("data.csv", index=False) # Export Dataframe
load_data = pd.read_csv("data.csv") # Import Dataframe
load_data

      Name  Age  Salery
0   Mahesh   20    5000
1     Arun   21    6000
2  Bhushan   22    7000
3     Amol   21    8000

## 4.Rows & Coloumns - Selection

In [49]:
df[['Name']] # select single coloums
df[['Name', 'Age']] # select double coloums

      Name  Age
0   Mahesh   20
1     Arun   21
2  Bhushan   22
3     Amol   21

In [70]:
# Loc - Label based index
df.loc[df.Name=='Mahesh']  # Select Single row
df.loc[0:2]  # Select Multiple row
df.loc[(df.Name == "Mahesh") & (df.Age > 18)]  # With condition

     Name  Age  Salery
0  Mahesh   20    5000

In [71]:
# iloc - index-value based
df.iloc[0] # Single row
df.iloc[0:2]  # For multiple rows [start:stop:step]

     Name  Age  Salery
0  Mahesh   20    5000
1    Arun   21    6000

In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[1:10:2]

array([ 2,  4,  6,  8, 10])

## 5. Filter Dataframe

In [96]:
df['Age'] > 20 # it return boolen true or false
df[df['Age'] > 20] # it directly return data

      Name  Age  Salery
1     Arun   21    6000
2  Bhushan   22    7000
3     Amol   21    8000

In [ ]:
df[(df['Age'] >= 18) & (df['Salery'] >= 5000)]

      Name  Age  Salery
0   Mahesh   20    5000
1     Arun   21    6000
2  Bhushan   22    7000
3     Amol   21    8000

In [97]:
df.where(df['Age'] > 21) # it return result without changing index

      Name   Age  Salery
0      NaN   NaN     NaN
1      NaN   NaN     NaN
2  Bhushan  22.0  7000.0
3      NaN   NaN     NaN

In [98]:
df.where(df['Age'] > 21, other='Not Eligible')

           Name           Age        Salery
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2       Bhushan            22          7000
3  Not Eligible  Not Eligible  Not Eligible

## 6. Rows and Coloums Operations (Add update delete)

In [ ]:
df['Team'] = ['CEO', 'HR', 'CTO', "DA"] # Adding new coloums
df

      Name  Age  Salery Team
0   Mahesh   20    5000  CEO
1     Arun   21    6000   HR
2  Bhushan   22    7000  CTO
3     Amol   21    8000   DA